spring.application.name=electric-bot
spring.datasource.url=jdbc:mysql://localhost:3306/electric_bot
spring.datasource.username=botuser
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect